spectaql:
  themeDir: "spectaql"

info:
  title: Helium GraphQL API Reference
  description: Documentation related to available types, queries, mutations, etc. in Helium
  termsOfService: https://www.thoughtindustries.com
  contact:
    name: Support
    url: http://www.thoughtindustries.com/support
    email: support@thoughtindustries.com
  license:
    name: MIT
    url: https://github.com/thoughtindustries/helium-graphql/blob/main/LICENSE.md
  x-url: https://example.thoughtindustries.com/helium

introspection:
  introspectionFile: ./graphql.schema.json
  metadataFile: ./metadata.json
  fieldExpansionDepth: 2
  dynamicExamplesProcessingModule: ./example-processor.js

extensions:
  graphqlScalarExamples: true