spectaql:
  themeDir: './custom-theme'

info:
  title: Helium GraphQL API Reference
  description: Documentation related to available types, queries, mutations, etc. in Helium.
  linkToAPIDocs: We also have a REST API with additional endpoints not covered in our GraphQL API. Documentation for the REST API can be found here https://api.thoughtindustries.com/#thought-industries-api.
  termsOfService: https://www.thoughtindustries.com
  rateLimits: The GraphQL API has a rate limit per hour. Find out more here https://developer.thoughtindustries.com/build/developer-guide#graphql-rate-limits
  contact:
    name: Get Support
    url: https://discord.gg/cTJBX4muVn
  license:
    name: MIT
    url: https://github.com/thoughtindustries/helium-graphql/blob/main/LICENSE.md
  x-url: https://example.thoughtindustries.com/helium

introspection:
  introspectionFile: ./graphql.schema.json
  metadataFile: ./metadata.json
  fieldExpansionDepth: 2
  dynamicExamplesProcessingModule: ./example-processor.js

extensions:
  graphqlScalarExamples: true
